//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoºMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class producto_imagen
    {
        public int id { get; set; }
        [Required(ErrorMessage = "El campo Imagen  es obligatorio")]
        public string imagen { get; set; }
        [Required(ErrorMessage = "El campo Id_Producto  es obligatorio")]
        public int id_producto { get; set; }
    
        public virtual producto producto { get; set; }
    }
}
